# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'assets/uiFiles/loading.ui'
#
# Created by: PySide6 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PySide6 import QtCore, QtGui, QtWidgets
import os
import sys
sys.path.append(os.path.join(os.path.dirname(__file__), '.'))
import loadingWindow_qrc


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(768, 384)
        Form.setStyleSheet("background-color: rgb(0, 8, 31);")
        self.gridLayout = QtWidgets.QGridLayout(Form)
        self.gridLayout.setObjectName("gridLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(Form)
        self.label.setMinimumSize(QtCore.QSize(0, 128))
        self.label.setStyleSheet("image: url(:/newPrefix/images/lets_code_logo.svg);\n"
"")
        self.label.setText("")
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setStyleSheet("color: rgb(255, 255, 255);\n"
"font: 75 28pt \"Sans\";\n"
"font-weight: 700;\n"
"margin: 16px;")
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2, 0, QtCore.Qt.AlignHCenter)
        self.progressBar = QtWidgets.QProgressBar(Form)
        self.progressBar.setStyleSheet("color: rgb(255, 255, 255);\n"
"font: 75 14pt \"Sans\";\n"
"font-weight: 700;\n"
"\n"
"")
        self.progressBar.setProperty("value", 0)
        self.progressBar.setObjectName("progressBar")
        self.verticalLayout.addWidget(self.progressBar, 0, QtCore.Qt.AlignVCenter)
        self.label_3 = QtWidgets.QLabel(Form)
        self.label_3.setStyleSheet("font: 12pt \"Sans\";\n"
"color: rgb(255, 255, 255);\n"
"")
        self.label_3.setObjectName("label_3")
        self.verticalLayout.addWidget(self.label_3, 0, QtCore.Qt.AlignHCenter)
        self.gridLayout.addLayout(self.verticalLayout, 0, 0, 1, 1)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)


        self._translate = QtCore.QCoreApplication.translate


    def setValues(self , value , tag):
        self.progressBar.setValue(value)
        self.label_3.setText(self._translate("Form", str(tag)))
        QtCore.QCoreApplication.processEvents()




                


    def retranslateUi(self, Form):
        self._translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(self._translate("Form", "iChatter"))
        self.label_2.setText(self._translate("Form", "Let\'s Code Technologies"))
        self.label_3.setText(self._translate("Form", ""))


if __name__ == "__main__":
    import sys

    # making the application look same across all platforms
    QtWidgets.QApplication.setStyle("Windows")

    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    

    import time
    for i in range(99):
        ui.setValues(i , i)
        time.sleep(0.5)

    sys.exit(app.exec_())
