# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainSetupPage.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import singupWindow_qrc


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(768, 488)
        Form.setMinimumSize(QtCore.QSize(768, 488))
        Form.setStyleSheet("background-color: rgb(0, 8, 31);")
        self.gridLayout = QtWidgets.QGridLayout(Form)
        self.gridLayout.setObjectName("gridLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.mainLogoLabel = QtWidgets.QLabel(Form)
        self.mainLogoLabel.setMinimumSize(QtCore.QSize(320, 180))
        self.mainLogoLabel.setStyleSheet("image: url(:/newPrefix/images/Group5.svg);\n"
"margin-left: auto;\n"
"margin-right: auto;")
        self.mainLogoLabel.setText("")
        self.mainLogoLabel.setObjectName("mainLogoLabel")
        self.verticalLayout.addWidget(self.mainLogoLabel)
        self.gridLayout.addLayout(self.verticalLayout, 0, 0, 1, 1)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.usernameLabel = QtWidgets.QLabel(Form)
        self.usernameLabel.setMinimumSize(QtCore.QSize(250, 40))
        self.usernameLabel.setMaximumSize(QtCore.QSize(16777215, 100))
        self.usernameLabel.setStyleSheet("color: rgb(255, 255, 255);\n"
"font: 16pt \"Consolas\";\n"
"height: 30%;\n"
"\n"
"")
        self.usernameLabel.setObjectName("usernameLabel")
        self.verticalLayout_2.addWidget(self.usernameLabel)
        self.userNameInput = QtWidgets.QLineEdit(Form)
        self.userNameInput.setMinimumSize(QtCore.QSize(250, 48))
        self.userNameInput.setStyleSheet("background-color: rgb(80, 80, 80);\n"
"color: rgb(255, 255, 255);\n"
"border-color: rgb(112, 112, 112);\n"
"font: 14pt \"Consolas\";\n"
"")
        self.userNameInput.setFrame(False)
        self.userNameInput.setObjectName("userNameInput")
        self.verticalLayout_2.addWidget(self.userNameInput)
        self.uepCheckbox = QtWidgets.QCheckBox(Form)
        self.uepCheckbox.setEnabled(True)
        self.uepCheckbox.setStyleSheet("color: rgb(139, 211, 206);\n"
"font: 14pt \"Consolas\";")
        self.uepCheckbox.setChecked(True)
        self.uepCheckbox.setObjectName("uepCheckbox")
        self.verticalLayout_2.addWidget(self.uepCheckbox)
        self.ContinueButton = QtWidgets.QPushButton(Form)
        self.ContinueButton.setMinimumSize(QtCore.QSize(128, 64))
        self.ContinueButton.setStyleSheet("background-color: rgb(120, 140, 222);\n"
"color: rgb(255, 255, 255);\n"
"font: 14pt \"Consolas\";\n"
"margin-left: 64px;\n"
"margin-right: 64px;\n"
"padding-top: 16px;\n"
"padding-bottom: 16px;\n"
"margin-bottom: 32px;\n"
"margin-top: 32px;\n"
"\n"
"")
        self.ContinueButton.setObjectName("ContinueButton")
        self.verticalLayout_2.addWidget(self.ContinueButton)
        self.gridLayout.addLayout(self.verticalLayout_2, 0, 1, 1, 1)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "iChatter - signUp"))
        self.usernameLabel.setText(_translate("Form", "Please Choose a Username :"))
        self.userNameInput.setPlaceholderText(_translate("Form", "username"))
        self.uepCheckbox.setText(_translate("Form", "user experience program"))
        self.ContinueButton.setText(_translate("Form", "CONTINUE"))



if __name__ == "__main__":
    import sys
    QtWidgets.QApplication.setStyle("Windows")
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
